# Generated by Django 5.1.7 on 2025-03-27 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customers',
            name='vat_number',
            field=models.CharField(default='TEMP_VAT', editable=False, max_length=15),
        ),
    ]
