# Generated by Django 5.1.7 on 2025-03-27 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_customers_vat_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customers',
            name='vat_number',
            field=models.CharField(editable=False, max_length=15),
        ),
    ]
