# Generated by Django 5.1.7 on 2025-03-27 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_alter_customers_vat_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='something',
            field=models.BooleanField(default=False),
        ),
    ]
