# Generated by Django 5.1.7 on 2025-03-27 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_product_something'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='something',
        ),
    ]
